### ISSUE TITLE
Adding a Snippet two times or more

### ISSUE THREAD

**Issue by godDLL** [svanlaere/easysnippet#4]
I work with the translation plugin and that takes `en` and `ru` Page-parts as input,
so I have to go about those translations splatting those Snippets everywhere,
and that combo menu is really getting to me.

It is impossible to insert the same Snippet twice without inserting some other Snippet.

Also, it really seems like a job for one click, instead of click-move-click;
_at least_ if your list of Snippets is short enough to fit on-screen, not taking it up entirely.

**Comment by godDLL** [comment]
I'm going to add an "Add again" button.

**Comment by godDLL** [comment]
And a "Button Mode" in the settings, that's how much I've come to hate that combo box in the last 15 minutes. I'll format it properly too. Dang.

**Comment by godDLL** [comment]
Yeah, now I'm done. :smile:

**Comment by svanlaere** [comment]
Merged the edits, strange enough I usually don't use this plugin myself.
